language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t bo100nka/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bo100nka/docker-react npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "docker-react-env"
  bucket_name: "elasticbeanstalk-eu-central-1-468703610761"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
